export const cols = {
  class6_8: [
    {
      title: "Bangla",
      dataIndex: "Bangla",
      key: "Bangla",
    },
    {
      title: "English",
      dataIndex: "English",
      key: "English",
    },
    {
      title: "Mathematics",
      dataIndex: "Mathematics",
      key: "Mathematics",
    },
    {
      title: "Religion",
      dataIndex: "Religion",
      key: "Religion",
    },
    {
      title: "Science",
      dataIndex: "Science",
      key: "Science",
    },
    {
      title: "History & Social Science",
      dataIndex: "History & Social Science",
      key: "History & Social Science",
    },
    {
      title: "Digital Technology",
      dataIndex: "Digital Technology",
      key: "Digital Technology",
    },
    {
      title: "Art & Crafts",
      dataIndex: "Art & Crafts",
      key: "Art & Crafts",
    },
    {
      title: "Wellbeing",
      dataIndex: "Wellbeing",
      key: "Wellbeing",
    },
    {
      title: "Life & Livelyhood",
      dataIndex: "Life & Livelyhood",
      key: "Life & Livelyhood",
    },
    {
      title: "grand",
      dataIndex: "grand",
      key: "grand",
    },
  ],
  class9_10: [
    {
      title: "Bangla",
      dataIndex: "Bangla",
      key: "Bangla",
      type: "common",
    },
    {
      title: "English",
      dataIndex: "English",
      key: "English",
      type: "common",
    },
    {
      title: "Mathematics",
      dataIndex: "Mathematics",
      key: "Mathematics",
      type: "common",
    },
    {
      title: "Religion",
      dataIndex: "Religion",
      key: "Religion",
      type: "common",
    },
    {
      title: "Science",
      dataIndex: "Science",
      key: "Science",
      type: "common",
    },
    {
      title: "Bangladesh & Global Studies",
      dataIndex: "Bangladesh & Global Studies",
      key: "Bangladesh & Global Studies",
      type: "common",
    },
    {
      title: "ICT",
      dataIndex: "ICT",
      key: "ICT",
      type: "common",
    },
    {
      title: "Physics",
      dataIndex: "Physics",
      key: "Physics",
      type: "science",
    },
    {
      title: "Chemistry",
      dataIndex: "Chemistry",
      key: "Chemistry",
      type: "science",
    },
    {
      title: "Biology",
      dataIndex: "Biology",
      key: "Biology",
      type: "science",
    },
    {
      title: "Higher Mathematics",
      dataIndex: "Higher Mathematics",
      key: "Higher Mathematics",
      type: "optional",
    },
    {
      title: "Accounting",
      dataIndex: "Accounting",
      key: "Accounting",
      type: "commerce",
    },
    {
      title: "Finance & Banking",
      dataIndex: "Finance & Banking",
      key: "Finance & Banking",
      type: "commerce",
    },
    {
      title: "Business Entrepreneurship",
      dataIndex: "Business Entrepreneurship",
      key: "Business Entrepreneurship",
      type: "commerce",
    },
    {
      title: "Civics & Good Governance",
      dataIndex: "Civics & Good Governance",
      key: "Civics & Good Governance",
      type: "arts",
    },
    {
      title: "Economics",
      dataIndex: "Economics",
      key: "Economics",
      type: "arts",
    },
    {
      title: "Geography",
      dataIndex: "Geography",
      key: "Geography",
      type: "arts",
    },
    {
      title: "Agriculture",
      dataIndex: "Agriculture",
      key: "Agriculture",
      type: "optional",
    },
    {
      title: "Home Science",
      dataIndex: "Home Science",
      key: "Home Science",
      type: "optional",
    },
    {
      title: "Computer Science",
      dataIndex: "Computer Science",
      key: "Computer Science",
      type: "optional",
    },
    {
      title: "Statistics",
      dataIndex: "Statistics",
      key: "Statistics",
      type: "optional",
    },
    {
      title: "grand",
      dataIndex: "grand",
      key: "grand",
    },
  ],
};
